### ISSUE TITLE
SQD tutorial: AttributeError: 'StatevectorSampler' object has no attribute 'options'

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/documentation#5040]
### URL to the relevant tutorial

https://quantum.cloud.ibm.com/docs/en/tutorials/sample-based-quantum-diagonalization
https://quantum.cloud.ibm.com/docs/en/tutorials/sample-based-krylov-quantum-diagonalization

### Select all that apply

- [ ] new content request
- [ ] typo
- [x] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix or the content request.

The buggy line
```python
sampler.options.environment.job_tags = ["TUT_SQD"]
```
was introduced in https://github.com/Qiskit/documentation/pull/4988. I guess the PR checks don't actually run the notebook?

### For new content requests - if the request is accepted, do you want to write the content?

I will write (or already have written) a draft of the proposed content
